### ISSUE TITLE
Consider moving the phase stop condition to the @run command

### ISSUE THREAD

**Issue by markusrobertjonsson** [markusrobertjonsson/learningsimulator#12]
Consider the ability to overrun the stop condition in a phase in (or in connection to) the @run command.

This allows @phase definitions without stop conditions, but then one has to specify them in (or in connection to) the @run command.

For example:
```
@run runlabel
    Phase: pre_training Stop_condition
    Phase: test Stop_condition
```

```
@run Runlabel
    New definitions (e.g. behaviors : left, right)
    Phase: Training Stop_condition
    New definitions (e.g. behaviors : left, right, back)
    Phase: Test Stop_condition
```

The last condition always applies (e.g. stop condition). Could be given outside @run:
```
Stop_condition
@run Runlabel
    Phases: Training,Test
```

**Comment by drghirlanda** [comment]
I think this is already possible using variables. For example, if the initial definition is:

     n_subjects: 10
    @phase myphase stop: new_trial=10

I think one can change the subject and stop conditions like this:

    n_subjects: 10
    @variables trial_number: 10
    @phase myphase stop: new_trial=trial_number
    @run myphase runlabel: first_run
    n_subjects: 20
    @variables trial_number: 20
    @run myphase runlabel: second_run

Although the proposed solution would be much shorter:

    @run myphase n_subjects: 10, stop: new_trial=10, runlabel: first_run
    @run myphase n_subjects: 20, stop: new_trial=20, runlabel: second_run

**Comment by markusrobertjonsson** [comment]
Moved to https://github.com/learningsimulator/learningsimulator/issues/89
