### ISSUE TITLE
Add progress bar

### ISSUE THREAD

**Issue by markusrobertjonsson** [markusrobertjonsson/learningsimulator#14]
Add a progress bar with a stop button during simulations.
    
Note that this can be done even without disconnecting the gui to the simulation process (which we might not do, anyway).

Tasks:
- [x] Add progress bar to GUI
- [ ] Add progress bar for command line runs

**Comment by markusrobertjonsson** [comment]
Merged pull request #71 .

**Comment by drghirlanda** [comment]
It would be great to have a progress indicator even for the command line application. Even something basic like printing a dot for each subject would be helpful.

**Comment by markusrobertjonsson** [comment]
Good point.

**Comment by drghirlanda** [comment]
@markusrobertjonsson I think there is something that does not work when running in command line mode. I get this error that seems related to the progress bar feature:

Traceback (most recent call last):
  File "/home/stefano/Dropbox/Software/lesim2/lesim.py", line 55, in <module>
    script_obj.postproc(simulation_data, block)
  File "/home/stefano/Dropbox/Software/lesim2/parsing.py", line 68, in postproc
    progress.dlg.set_visibility2(False)
AttributeError: 'bool' object has no attribute 'dlg'

**Comment by markusrobertjonsson** [comment]
@drghirlanda Fixed.

**Comment by markusrobertjonsson** [comment]
Moved to https://github.com/learningsimulator/learningsimulator/issues/104
