### ISSUE TITLE
Include phase line labels in @hexported file

### ISSUE THREAD

**Issue by markusrobertjonsson** [markusrobertjonsson/learningsimulator#31]
A suggestion is to include phase line labels (including help lines) as a new column in the output csv file from hexport. Maybe change the name of the "step" column, as this is not really steps (a stimulus-response pair) anymore.

**Comment by drghirlanda** [comment]
I second the idea of including phase lines and perhaps even phase names to make the CSV files easier to parse for external programs without having to look up details of the script. If we don't want to add too many extra columns, we can go with something like <phase name>:<line name> in a column named "phase line subject i" or similar.

This will make it easier to check whether a script is running as intended and it will make plotting and analysis by external programs easier.

**Comment by markusrobertjonsson** [comment]
Moved to https://github.com/learningsimulator/learningsimulator/issues/115
