### ISSUE TITLE
Extend plot/export expressions to allow arithemtic

### ISSUE THREAD

**Issue by markusrobertjonsson** [markusrobertjonsson/learningsimulator#34]
A suggestion is to introduce a general @plot function that takes an expression with v-, w-, and p-values. For example

@plot v(s1->b1)*v(s2->b2)

The current @vplot, @pplot, and @wplot should remain, for example,
@vplot s->b
is a shorthand for @plot v(s->b).
    
(Same for @export.)

**Comment by drghirlanda** [comment]
This would be a useful feature but we should also only allow operations that make sense. For example, it would be useful to add or substract v and/or w values, but multiplying them is unlikely to make sense. On the other hand, both adding/subtracting and multiplying can be useful for probabilities.

**Comment by markusrobertjonsson** [comment]
@drghirlanda But multiplying p-values can make sense, right? (@plot p(s1->b1)*p(s2->b2))

**Comment by markusrobertjonsson** [comment]
Moved to https://github.com/learningsimulator/learningsimulator/issues/103
