### ISSUE TITLE
It should be possible to save figures from script

### ISSUE THREAD

**Issue by drghirlanda** [markusrobertjonsson/learningsimulator#41]
It would be useful to be able to save figures to PNG, PDF, or other suported formats from a script, for example providing a 'filename':'myfigure.pdf' entry to the @figure options dictionary. This will make it possible to generate figures during unattended batch jobs, for example for long simulations or when generating many figures.

**Comment by markusrobertjonsson** [comment]
Moved to https://github.com/learningsimulator/learningsimulator/issues/121
