### ISSUE TITLE
Set default ylim for @pplot

### ISSUE THREAD

**Issue by drghirlanda** [markusrobertjonsson/learningsimulator#42]
When plotting response probabilities, it could be useful to set the default y range to [0,1] to appreciate immediately the probability of behavior.

**Comment by markusrobertjonsson** [comment]
Since several different plot types can be present in the same subplot, I guess we should set the default ylim to [0,1] if there are only @pplot:s present in the subplot. What should be the ylim for the graph produced by the following?
```
@pplot s->b1
@vplot s->b2
```

**Comment by drghirlanda** [comment]
Yes, unless all is `@pplot` the limit should not be [0,1]. By the way, I find [-0.025,1.025] or similar more convenient because it allows 0 and 1 probabilities to be more clearly visible (they disappear under the axis with [0,1] unless the line is thick).

**Comment by markusrobertjonsson** [comment]
Moved to https://github.com/learningsimulator/learningsimulator/issues/122
