### ISSUE TITLE
Enhancements in initial value declarations

### ISSUE THREAD

**Issue by drghirlanda** [markusrobertjonsson/learningsimulator#46]
We often need to set v_start values for more than one stimulus to a given behavior:

    v_start: s1->other:1, s2->other:1, s3->other:1, default:0

It would be convenient to be able to write:

    v_start: *->other:1, default:0

which is more readable in addition to being shorter to type.

**Comment by markusrobertjonsson** [comment]
Moved to learningsimulator repo.
