### ISSUE TITLE
Introduce @block and @addblock to decrease repetition

### ISSUE THREAD

**Issue by drghirlanda** [markusrobertjonsson/learningsimulator#47]
It seems common to reuse several @phase lines in different phases. To save code duplication and decrease potential mistakes, it may be useful to be able to save these lines and add them to phases. For example:

    @block someLines
    LINE1 ...
    LINE2 ...

and then:

    @phase phase1 ...
    @addblock someLines
    LINE3 ...

    @phase phase2 ...
    @addblock someLInes
    LINE4 ...
    
This would be more flexible than the current @phase inheritance mechanism, because it would be possible to use multiple blocks in each phase. It should still be possible to overwrite lines as it is possible now.

**Comment by markusrobertjonsson** [comment]
@drghirlanda Doesn't this also require an @endblock keyword, to determine where the block ends?    
Also, do you mean that the current phase2(phase1) inheritance should be kept?

**Comment by drghirlanda** [comment]
I don't think we need `@endblock` because the end of the block can be determined in the same way as the end of `@phase`, right? I guess this is until the next keyword is found. Do you see nay problem in the following?

    @block block1
    LINE 1
    LINE 2

    @block block2
    LINE 3
    LINE 4

    @phase just1
    @addblock block1

    @phase both
    @addblock block1
    @addblock block2

I don't have a strong opinion about phase inheritance staying or going. However, if the name of a phase is admissible as a block name, inheritance could be replaced by using @addblock and the phase you want to inherit from.

**Comment by markusrobertjonsson** [comment]
@drghirlanda Ah, I see. I thought you wanted @block *inside* a phase. Two questions:
- Do you think there is a need for the use of @block where the block contains other things than phase lines?
- If @block would replace the current inheritance, did you mean that it should be used liks this?:
```
@block block1
LINE1
LINE2
...
LINEn

@phase phase1 stop:a=1
@addblock block1

@phase phase2 stop:a=1
@addblock block1
LINE2 new_content_on_LINE2
```

**Comment by drghirlanda** [comment]
Yes, that's what I add in mind!

**Comment by markusrobertjonsson** [comment]
Moved to https://github.com/learningsimulator/learningsimulator/issues/126
