### ISSUE TITLE
introduce @end keyword

### ISSUE THREAD

**Issue by drghirlanda** [markusrobertjonsson/learningsimulator#48]
It is sometimes convenient to have a "junkyard" of code bits in a script, or to quickly disable execution of everything past a certain point when making changes to a script. An `@end` keyword that instructs the parser to stop parsing would be useful in this context.

**Comment by markusrobertjonsson** [comment]
An alternative would be to let the first "###" mean "start comment", the second "end comment", and so on. And there does not have to be an "end comment" matching a "start comment".
```
mechanism: GA
u: 1
###
A block
comment
###
beta:1

###
Junk yard
This part of the script
will be ignored.
```

**Comment by drghirlanda** [comment]
Yes, that would work too!

**Comment by markusrobertjonsson** [comment]
(But it won't work if the junkyard already contains "###"-block comments.)

**Comment by markusrobertjonsson** [comment]
Moved to https://github.com/learningsimulator/learningsimulator/issues/127
