### ISSUE TITLE
Syntactic sugar in phase lines

### ISSUE THREAD

**Issue by drghirlanda** [markusrobertjonsson/learningsimulator#56]
A suggestions to shorten phase lines: * could be used for "this line":

    MY_LONG_LINE s | count(MY_LONG_LINE)>10: OTHER_LINE | MY_LONG_LINE

would become:

    MY_LONG_LINE s | count(*)>10: OTHER_LINE | *

The last bit is also visually distinctive and signals that the line will repeat if the other conditions are not triggered.

**Comment by markusrobertjonsson** [comment]
@drghirlanda count(MY_LONG_LINE) can already be shortened to count_line(). However, there is no shorthand for the last MY_LONG_LINE.
    
(count(x) is a phase-wide global counter (which can be reset using count_reset(x)) whereas count_line counts consecutive events on a line.)

Perhaps we should use something else than *, considering issue #46, where * would mean "all" in a sense?

**Comment by drghirlanda** [comment]
Great, thanks for the info. I don't think the | * thing is crucial.
