### ISSUE TITLE
@hexport does not align columns properly

### ISSUE THREAD

**Issue by drghirlanda** [markusrobertjonsson/learningsimulator#57]
It seems that @hexport runs into trouble when exporting multiple subjects with histories of different length. At step 421 of the attached file, a single empty line appears as the first field after the step number, which throws off the correspondence of stimulus and response fields to column names. 

[Skinner1934.txt](https://github.com/markusrobertjonsson/lesim2/files/3134663/Skinner1934.txt)

**Comment by markusrobertjonsson** [comment]
Fixed in e5872923f80896ffb5cdc1984f39823288bcd7ae.
