### ISSUE TITLE
Shorthand in alpha and beta specifications

### ISSUE THREAD

**Issue by drghirlanda** [markusrobertjonsson/learningsimulator#65]
The ability to specify alpha_v and alpha_w is very useful to tune learning to stimulus and response characteristics. A similar feature is planned for beta. It could be useful to add a shorthand, for example *, to mean all stimuli or all behaviors in these dictionaries. For example if stimulus S is assumed to be of very low intensity, one may want to reduce alpha_v for all responses to this stimulus, in which case one could write:

    alpha_v: S->*:0.01, default: 0.1

instead of listing all behaviors. Conversely, if a behavior is predisposed one could model this with a high alpha for all v values involving that behavior:

    alpha_v: *->B:0.2, default 0.1

**Comment by markusrobertjonsson** [comment]
@drghirlanda Is this the same suggestion as in #46 (Enhancements in initial value declarations), but for other parameters? If we introduce *, it will be available for all parameters indexed by stimulus-response pairs, I guess.

**Comment by drghirlanda** [comment]
Yes, you're right, it would be the same!

**Comment by markusrobertjonsson** [comment]
Moved to https://github.com/markusrobertjonsson/learningsimulator/issues/127
