### ISSUE TITLE
Make @end_trial (or @omit_update(v)) replace the new_trial functionality

### ISSUE THREAD

**Issue by markusrobertjonsson** [markusrobertjonsson/learningsimulator#80]
Proposal from Magnus:

We take away new_trail and replace it with an end_trial keyword 
like this

 ```
@phase ....
START ...
...
REWARD       reward     | @end_trial
NO_REWARD    no_reward  | @end_trial
```
This has four consequences:

1. w(reward) and w(no_reward) are not updated
2. v(reward->whatever response) and v(no_reward-> whatever response) are 
not updated
3. end_trial is logged by the program but no arbitrary response to e.g 
reward is logged
4. Jumps to the beginning of the script (we might increase the 
functionality here and allow jumps to anywhere).

We still keep the binding on/off options so we can quickly switch

To me this is more clear in several ways than the new_trial solution. 
First, it is very clear where things operate, the stimulus is on the 
same row as the ``end_trial`` keyword. Second, it also becomes more clear 
that one must end the trial properly supplying reinforcement to all 
outcomes.

Perhaps the keyword ``@end_trial`` can be replaced by ``@omit_update(v)``
or something like that which can be used to control which state variables to 
avoid updating. 

After issue #92 is done, we may need a @cleartrace to flush the trace memory, in the same way.

- [x] Add unit tests of trace that compares both "learning to respond to a stimulus" and "learning a chain" with and without trace (with and without @cleartrace), and with and without conditional reinforcment (w) (in other words, compare SR to A-learning (GA)).

**Comment by drghirlanda** [comment]
Regarding point 3, I would still log what response is chosen. I think it's best not to throw away information.

**Comment by markusrobertjonsson** [comment]
Addressed. See https://github.com/learningsimulator/learningsimulator/issues/162 for remaining issue.
