### ISSUE TITLE
Use of local and global variables

### ISSUE THREAD

**Issue by drghirlanda** [markusrobertjonsson/learningsimulator#83]
It seems that the use of global variables has these features, I am not sure they are intended:

1. Global variables (introduced with @variables) cannot be modified in help lines within phases. This gives an error:

    @variables p:1
     ...
     LINE0 p:0.5 | LINE1
     ...

2. Local variables (introduced in help lines) can be modified, but cannot be used to specify transition probabilities. This gives an error:
    
    LINE0 p:0.5        | LINE1
    LINE1 stimulus1 | LINE2(p) | LINE3
    ...

I discovered this because I needed a setup in which the transition probability changes over time, and I tried both arrangements.

**Comment by markusrobertjonsson** [comment]
@drghirlanda 1 is per design. 2 is a bug (local variables are not supported in the probabilities).

**Comment by markusrobertjonsson** [comment]
Local variables are now supported in probabilities. Fixed on issue branch 92. Merged to master.
