### ISSUE TITLE
Script window freezes in mac (macOS 10.14.6)

### ISSUE THREAD

**Issue by johanoloflind** [markusrobertjonsson/learningsimulator#86]
After a simulations has been run and a graph or an error window is displayed the script window freezes. It comes alive again after graph or error message window(s) are closed.
With macOS 10.14.6 and Python 3.7.3.

**Comment by markusrobertjonsson** [comment]
The error dialog box _should_ freeze the script window. But the figure windows with graphs should not. Seems to be a mac specific issue. (Cannot reproduce on Python 3.7.5 on Ubuntu 18.04.)

**Comment by markusrobertjonsson** [comment]
Perhaps using plt.ion() is a solution? (https://stackoverflow.com/questions/28269157/plotting-in-a-non-blocking-way-with-matplotlib)

**Comment by markusrobertjonsson** [comment]
Fixed (in 8e60a56) by plotting in a non-blocking way on Mac.
